//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampa.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AmpaEntities : DbContext
    {
        public AmpaEntities()
            : base("name=AmpaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumnos { get; set; }
        public virtual DbSet<Curso> Cursos { get; set; }
        public virtual DbSet<CursosSocio> CursosSocios { get; set; }
        public virtual DbSet<HistoricoAlumno> HistoricoAlumnos { get; set; }
        public virtual DbSet<Socio> Socios { get; set; }
        public virtual DbSet<Tutore> Tutores { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
