//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursosSocio
    {
        public int CursoId { get; set; }
        public int SocioId { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> PagoPorBanco { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Socio Socio { get; set; }
    }
}
