//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoAlumno
    {
        public int Id { get; set; }
        public int CursoId { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Curso { get; set; }
        public Nullable<int> SocioId { get; set; }
    
        public virtual Curso Curso1 { get; set; }
        public virtual Socio Socio { get; set; }
    }
}
